// AUTO-GENERATED by scripts/gen-catalog.mjs from the reference sheet.
// Raw tab gid=1386199877, WIP tab gid=310552156. Do not edit by hand; re-run the generator.

export type StockGroup = "raw_material" | "wip";

export type CatalogItem = {
  id: string;
  name: string;
  unit: string;
  note?: string;
  hasImage?: boolean;
};

export type CatalogEntry = {
  title: string;
  eyebrow: string;
  copy: string;
  items: CatalogItem[];
};

export const stockCatalog: Record<StockGroup, CatalogEntry> = {
  raw_material: {
    title: "นับ Stock รายวัน",
    eyebrow: "Raw Material",
    copy: "วัตถุดิบคงเหลือทั้งหมด — เนื้อสัตว์ ผัก อาหารทะเล เครื่องปรุง และของแช่แข็ง",
    items: [
          {
                "id": "r1",
                "name": "เนื้อหมูสันคอ",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r2",
                "name": "เนื้อหมูสันนอก",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r3",
                "name": "เนื้อสามชั้น",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r4",
                "name": "เนื้อวัวสันคอ",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r5",
                "name": "เนื้อวัวริบอาย",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r6",
                "name": "เนื้อวัวออส",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r7",
                "name": "สะโพกหมู",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r8",
                "name": "ไส้อ่อนหมู",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r9",
                "name": "เบค่อน",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r10",
                "name": "ผักกวางตุ้ง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r11",
                "name": "ผักบุ้ง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r12",
                "name": "ผักกาดขาว",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r13",
                "name": "เห็ดชิเมจิ",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r14",
                "name": "เห็ดเข็มทอง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r15",
                "name": "ฟักทอง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r16",
                "name": "มันฝรั่ง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r17",
                "name": "ข้าวโพดอ่อน",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r18",
                "name": "ข้าวโพดหวาน",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r19",
                "name": "หัวไชเท้า",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r20",
                "name": "แครอท",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r21",
                "name": "ผักชีไทย",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r22",
                "name": "กะหล่ำปลี",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r23",
                "name": "กระเจี๊ยบ",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r24",
                "name": "เต้าหู้ไข่ไก่",
                "unit": "หลอด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r25",
                "name": "ขิงอ่อน",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r26",
                "name": "พริกจินดาแดง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r27",
                "name": "กระเทียมปอก",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r28",
                "name": "เลือดไก่",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r29",
                "name": "น้ำปลา",
                "unit": "ขวด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r30",
                "name": "น้ำพริกเผา",
                "unit": "กระป๋อง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r31",
                "name": "ซอสหอย",
                "unit": "ขวด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r32",
                "name": "พริกแห้ง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r33",
                "name": "ตะไคร้",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r34",
                "name": "ข่าอ่อน",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r35",
                "name": "ใบมะกรูด",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r36",
                "name": "น้ำมะนาว",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r37",
                "name": "พริกจินดาเขียว",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r38",
                "name": "เกลือ",
                "unit": "มัด",
                "note": "1 มัด มี 12 ถุง",
                "hasImage": false
          },
          {
                "id": "r39",
                "name": "น้ำตาลทราย",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r40",
                "name": "เฉาก๊วย",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r41",
                "name": "น้ำเขียว",
                "unit": "ขวด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r42",
                "name": "น้ำแดง",
                "unit": "ขวด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r43",
                "name": "น้ำมันพืช",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r44",
                "name": "เส้นแก้ว",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r45",
                "name": "เส้นหมี่หยก",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r46",
                "name": "บร็อคโคลี่",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r47",
                "name": "แตงโม",
                "unit": "ลูก",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r48",
                "name": "น้ำส้มสายชู",
                "unit": "ขวด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r49",
                "name": "ซีอิ๊วขาว",
                "unit": "ขวด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r50",
                "name": "ผักชีฝรั่ง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r51",
                "name": "กุนเชียง",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r52",
                "name": "นมคาเนชั่น",
                "unit": "กระป๋อง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r53",
                "name": "เส้นมาม่า",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r54",
                "name": "ไก่ยอ",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r55",
                "name": "อกไก่หมักงา",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r56",
                "name": "หมูหมักงา / สะโพกหมู",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r57",
                "name": "แมงกะพรุน",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r58",
                "name": "ปลาหมึกกรอบ",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r59",
                "name": "กุ้งขาว",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r60",
                "name": "ปลาดอลลี่",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": true
          },
          {
                "id": "r61",
                "name": "เต้าหู้ชีส",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r62",
                "name": "ชิกูวะ",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r63",
                "name": "ฟองเต้าหู้ซีฟู้ด",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r64",
                "name": "ปูจ๋าไข่แดง",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r65",
                "name": "ไส้กรอกแดง",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r66",
                "name": "นักเก็ต",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r67",
                "name": "เฟรนส์ฟราย",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r68",
                "name": "ไส้เป็ด",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r69",
                "name": "สไบนาง",
                "unit": "กิโลกรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r70",
                "name": "ปูอัด",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r71",
                "name": "ฟองเต้าหู้ม้วนทอด",
                "unit": "แพ็ค",
                "note": "1 ลัง มี 32 แพ็ค",
                "hasImage": false
          },
          {
                "id": "r72",
                "name": "ฟองเต้าหู้เหลี่ยม",
                "unit": "ลัง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r73",
                "name": "เส้นเล็กหม่าล่า",
                "unit": "มัด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r74",
                "name": "เส้นมันเทศ",
                "unit": "แพ็ค",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r75",
                "name": "สาหร่ายวากาเมะ",
                "unit": "ห่อ",
                "note": "",
                "hasImage": false
          },
          {
                "id": "r76",
                "name": "ก้อนหม่าล่า",
                "unit": "ก้อน",
                "note": "",
                "hasImage": false
          }
    ],
  },
  wip: {
    title: "นับ Stock WIP รายวัน",
    eyebrow: "Work In Process",
    copy: "ของเตรียมแล้ว ชุดเกาเหลา และรายการของเสีย (waste)",
    items: [
          {
                "id": "w1",
                "name": "หมูสันคอ",
                "unit": "ถาด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w2",
                "name": "หมูสันนอก",
                "unit": "ถาด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w3",
                "name": "สามชั้น",
                "unit": "ถาด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w4",
                "name": "เนื้อสันคอ",
                "unit": "ถาด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w5",
                "name": "เนื้อริบอาย",
                "unit": "ถาด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w6",
                "name": "เนื้อออส",
                "unit": "ถาด",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w7",
                "name": "ชุดเกาเหลาหมู ธรรมดา",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w8",
                "name": "ชุดเกาเหลาหมู พิเศษ",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w9",
                "name": "ชุดเกาเหลาวัว ธรรมดา",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w10",
                "name": "ชุดเกาเหลาวัว พิเศษ",
                "unit": "ถุง",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w11",
                "name": "ของเสีย หมูสันคอ",
                "unit": "กรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w12",
                "name": "ของเสีย หมูสันนอก",
                "unit": "กรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w13",
                "name": "ของเสีย หมูสามชั้น",
                "unit": "กรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w14",
                "name": "ของเสีย เนื้อสันคอ",
                "unit": "กรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w15",
                "name": "ของเสีย  เนื้อออส",
                "unit": "กรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w16",
                "name": "ของเสีย  เนื้อริบอาย",
                "unit": "กรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w17",
                "name": "ของเสีย เนื้อริบอาย",
                "unit": "กรัม",
                "note": "",
                "hasImage": false
          },
          {
                "id": "w18",
                "name": "ของเสีย เนื้อออส",
                "unit": "กรัม",
                "note": "",
                "hasImage": false
          }
    ],
  },
};
