// Generates lib/catalog.ts from the reference Google Sheet headers.
// Raw tab gid=1386199877, WIP tab gid=310552156.
// Run: node scripts/gen-catalog.mjs
import fs from "node:fs";
import path from "node:path";

const SPREADSHEET_ID = "1yCTt20qio0UEZfw_LW4-G6e3xbdg_r266yB5VYb3ebs";
const TABS = { raw_material: "1386199877", wip: "310552156" };

function parseCsvLine(line) {
  const out = [];
  let cur = "";
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (q) {
      if (c === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i++;
        } else q = false;
      } else cur += c;
    } else if (c === '"') q = true;
    else if (c === ",") {
      out.push(cur);
      cur = "";
    } else if (c !== "\r") cur += c;
  }
  out.push(cur);
  return out;
}

async function fetchHeader(gid) {
  const url = `https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/gviz/tq?tqx=out:csv&gid=${gid}`;
  const res = await fetch(url);
  const text = await res.text();
  return parseCsvLine(text.split("\n")[0]);
}

function buildItems(cols, prefix) {
  const items = [];
  let n = 0;
  for (let i = 3; i < cols.length; i++) {
    const raw = cols[i].trim();
    if (!raw) continue;
    if (raw === "แนบรูปประกอบ") {
      if (items.length) items[items.length - 1].hasImage = true;
      continue;
    }
    if (/^คอลัมน์\s*\d+$/.test(raw)) continue;
    const m = raw.match(/^(.*?)\s*\(([^)]*)\)\s*(.*)$/);
    const name = (m ? m[1] : raw).trim();
    const unit = (m ? m[2] : "").trim();
    const note = (m ? m[3] : "").replace(/^[-\s]+/, "").trim();
    if (items.some((it) => it.name === name && it.unit === unit)) continue; // dedupe
    n += 1;
    items.push({ id: `${prefix}${n}`, name, unit, note, hasImage: false });
  }
  return items;
}

const raw = buildItems(await fetchHeader(TABS.raw_material), "r");
const wip = buildItems(await fetchHeader(TABS.wip), "w");

// Requirement: waste (ของเสีย) items support attaching a photo.
wip.forEach((it) => {
  if (it.name.startsWith("ของเสีย")) it.hasImage = true;
});

// Requirement: "รับเข้าวัตถุดิบ" (Raw Material Import) section — 6 meat cuts in
// kilograms, each with a photo. Not in the reference sheet; defined here.
const importItems = [
  { id: "i1", name: "หมูสันคอ", unit: "กิโลกรัม", note: "", hasImage: true },
  { id: "i2", name: "หมูสันนอก", unit: "กิโลกรัม", note: "", hasImage: true },
  { id: "i3", name: "สามชั้น", unit: "กิโลกรัม", note: "", hasImage: true },
  { id: "i4", name: "เนื้อสันคอ", unit: "กิโลกรัม", note: "", hasImage: true },
  { id: "i5", name: "เนื้อริบอาย", unit: "กิโลกรัม", note: "", hasImage: true },
  { id: "i6", name: "เนื้อออส", unit: "กิโลกรัม", note: "", hasImage: true },
];

const ts = `// AUTO-GENERATED by scripts/gen-catalog.mjs from the reference sheet.
// Raw tab gid=1386199877, WIP tab gid=310552156. Do not edit by hand; re-run the generator.

export type StockGroup = "raw_material" | "wip" | "import";

export type CatalogItem = {
  id: string;
  name: string;
  unit: string;
  note?: string;
  hasImage?: boolean;
};

export type CatalogEntry = {
  title: string;
  eyebrow: string;
  copy: string;
  items: CatalogItem[];
};

export const stockCatalog: Record<StockGroup, CatalogEntry> = {
  raw_material: {
    title: "นับ Stock รายวัน",
    eyebrow: "Raw Material",
    copy: "วัตถุดิบคงเหลือทั้งหมด — เนื้อสัตว์ ผัก อาหารทะเล เครื่องปรุง และของแช่แข็ง",
    items: ${JSON.stringify(raw, null, 6).replace(/\n/g, "\n    ")},
  },
  wip: {
    title: "นับ Stock WIP รายวัน",
    eyebrow: "Work In Process",
    copy: "ของเตรียมแล้ว ชุดเกาเหลา และรายการของเสีย (waste) — แนบรูปของเสียได้",
    items: ${JSON.stringify(wip, null, 6).replace(/\n/g, "\n    ")},
  },
  import: {
    title: "รับเข้าวัตถุดิบ",
    eyebrow: "Raw Material Import",
    copy: "บันทึกวัตถุดิบที่รับเข้า (เนื้อสัตว์) พร้อมแนบรูปทุกตัว",
    items: ${JSON.stringify(importItems, null, 6).replace(/\n/g, "\n    ")},
  },
};
`;

const outPath = path.join(process.cwd(), "lib", "catalog.ts");
fs.writeFileSync(outPath, ts, "utf8");
console.log(`Raw items: ${raw.length}`);
console.log(`WIP items: ${wip.length}`);
console.log(`Raw with image: ${raw.filter((i) => i.hasImage).length}`);
console.log(`Wrote ${outPath}`);
